package cl.model.pojos;
// Generated 31/07/2016 18:38:38 by Hibernate Tools 4.3.1



/**
 * Publicidad generated by hbm2java
 */
public class Publicidad  implements java.io.Serializable {


     private Integer pubId;
     private Marca marca;
     private char sexo;
     private byte edadMin;
     private byte edadMax;
     private byte horarioMin;
     private byte horarioMax;
     private byte[] imagen;

    public Publicidad() {
    }

    public Publicidad(Marca marca, char sexo, byte edadMin, byte edadMax, byte horarioMin, byte horarioMax, byte[] imagen) {
       this.marca = marca;
       this.sexo = sexo;
       this.edadMin = edadMin;
       this.edadMax = edadMax;
       this.horarioMin = horarioMin;
       this.horarioMax = horarioMax;
       this.imagen = imagen;
    }
                 
    public Integer getPubId() {
        return this.pubId;
    }
    
    public void setPubId(Integer pubId) {
        this.pubId = pubId;
    }
    public Marca getMarca() {
        return this.marca;
    }
    
    public void setMarca(Marca marca) {
        this.marca = marca;
    }
    public char getSexo() {
        return this.sexo;
    }
    
    public void setSexo(char sexo) {
        this.sexo = sexo;
    }
    public byte getEdadMin() {
        return this.edadMin;
    }
    
    public void setEdadMin(byte edadMin) {
        this.edadMin = edadMin;
    }
    public byte getEdadMax() {
        return this.edadMax;
    }
    
    public void setEdadMax(byte edadMax) {
        this.edadMax = edadMax;
    }
    public byte getHorarioMin() {
        return this.horarioMin;
    }
    
    public void setHorarioMin(byte horarioMin) {
        this.horarioMin = horarioMin;
    }
    public byte getHorarioMax() {
        return this.horarioMax;
    }
    
    public void setHorarioMax(byte horarioMax) {
        this.horarioMax = horarioMax;
    }
    public byte[] getImagen() {
        return this.imagen;
    }
    
    public void setImagen(byte[] imagen) {
        this.imagen = imagen;
    }




}


